package com.dws.otica.model.entity;
// Generated 04/04/2017 21:28:55 by Hibernate Tools 4.3.1



/**
 * Telefone generated by hbm2java
 */
public class Telefone  implements java.io.Serializable {


     private Integer idTelefone;
     private Cliente cliente;
     private String telefone;
     private char tipo;

    public Telefone() {
    }

    public Telefone(Cliente cliente, String telefone, char tipo) {
       this.cliente = cliente;
       this.telefone = telefone;
       this.tipo = tipo;
    }
   
    public Integer getIdTelefone() {
        return this.idTelefone;
    }
    
    public void setIdTelefone(Integer idTelefone) {
        this.idTelefone = idTelefone;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public char getTipo() {
        return this.tipo;
    }
    
    public void setTipo(char tipo) {
        this.tipo = tipo;
    }




}


