package com.dws.otica.model.entity;
// Generated 04/04/2017 21:28:55 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

    private Integer idUsuario;
    private String nome;
    private String email;
    private String senha;
    private String senhaProvisoria;
    private Character ativo;
    private Date dtAtivacao;
    private Date criadoEm;
    
    public Usuario() {
    }

    public Usuario(String nome, String email, Date criadoEm) {
        this.nome = nome;
        this.email = email;
        this.criadoEm = criadoEm;
    }

    public Usuario(String nome, String email, String senha, String senhaProvisoria, Character ativo, Date dtAtivacao, Date criadoEm) {
        this.nome = nome;
        this.email = email;
        this.senha = senha;
        this.senhaProvisoria = senhaProvisoria;
        this.ativo = ativo;
        this.dtAtivacao = dtAtivacao;
        this.criadoEm = criadoEm;
    }

    public Integer getIdUsuario() {
        return this.idUsuario;
    }

    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getSenha() {
        return this.senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }

    public String getSenhaProvisoria() {
        return this.senhaProvisoria;
    }

    public void setSenhaProvisoria(String senhaProvisoria) {
        this.senhaProvisoria = senhaProvisoria;
    }

    public Character getAtivo() {
        return this.ativo;
    }

    public void setAtivo(Character ativo) {
        this.ativo = ativo;
    }

    public Date getDtAtivacao() {
        return this.dtAtivacao;
    }

    public void setDtAtivacao(Date dtAtivacao) {
        this.dtAtivacao = dtAtivacao;
    }

    public Date getCriadoEm() {
        return this.criadoEm;
    }

    public void setCriadoEm(Date criadoEm) {
        this.criadoEm = criadoEm;
    }
}
